# -*- coding: utf-8 -*-
"""App AMA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jix8hODPSC-nPNe7_iJuf6W2a_NwJLxF
"""

#!pip install streamlit

# Importamos las librerías
import streamlit as st
import pandas as pd

st.title ("Mi primera App en Streamlit")
